includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/resnet12_emd.yaml

train_episode: 100
epoch: 100
episode_size: 1
batch_size: 128
way_num: 5
shot_num: 1
query_num: 1

test_episode: 100
test_epoch: 5
test_way: 5
test_shot: 1
test_query: 1

pretrain_path: results/deepemd_pretrain_model/miniimagenet/resnet12/max_acc.pth
data_root: ./data/fewshot/miniImageNet--ravi


classifier:
  kwargs:
    feat_dim: 640
    lambda_epi: 0.25
    num_classes: 64
    temperature: 0.2
    temperature_attn: 5.0
    mode: pretrain
    args:
      norm: center
      way: 5
      shot: 1
      query: 1
      deepemd: fcn
      solver: opencv
      num_patch: 9
      sfc_lr: 0.1
      sfc_bs: 4
      temperature: 12.5
      form: L2
      metric: cosine
      l2_strength: 0.000001

  name: DeepEMD
  
  


# lr_scheduler:
#   kwargs:
#     T_max: 100
#     eta_min: 0
#   name: CosineAnnealingLR

# optimizer:
#   kwargs:
#     lr: 0.1
#     momentum: 0.9
#     nesterov: true
#     weight_decay: 0.0005
#   name: SGD
#   other:
#     emb_func: 0.1


  
